### ISSUE TITLE
Different Amount of Maks in training and test time

### ISSUE THREAD

**Issue by AdrianoFonseca** [sangwoomo/instagan#54]
I used instagan with one mask on the A and B sets, during testing time I tried two mask on the A dataset and got very bad results. Did you try using different amounts of mask in training and test time? In your training did all the images in the same set have the same number of masks? (Great work btw!)

**Comment by sangwoomo** [comment]
Hi Adriano, thank you for your interest in our paper!

1. It is hard to generalize to unseen domains; hence you'd better also train with mask >= 2. In my experiments, training images contain {K >= and >= 1} masks for sufficiently large K.

2. To keep your background, you may try (1) cut the foregrounds, (2) modify them, and (3) paste them to the original background. I did not use it since it losses the harmony of the foregrounds/background, though.
