### ISSUE TITLE
Can InstaGAN be used for minor attribute manipulation?

### ISSUE THREAD

**Issue by kartikeyporwal** [sangwoomo/instagan#58]
Thank you so much for this amazing project.

I'm new in GANs, have got a usecase and I think my search stop at InstaGAN, not pretty sure though!

I can have manually created paired dataset to build Image to Image translation for changing only small part of the hair from head without making any other changes in the image.

I did have a glance at the paper and could figure out the steps as
1. Get the images with distorted/invalid type of hair on head, will act as x.
2. Manually generate mask of the hair part from invalid images, will act as a.
3. Get the images with valid/optimized hair on head, will act as y.
4. Manually generate mask of the hair part from valid images, will act as b.
5. Train model, it should translate from (x, a) to (y, b). 

InstaGAN is unpaired image to image translation, should it be working for paired dataset?
Images in x and y are nearly same with only minute changes in hair on head. Is it going to work?

Could you please help me knowing whether I'm moving in the right direction or missing something?

Thanks a ton.

**Comment by sangwoomo** [comment]
Hi,

I think InstaGAN would fit your problem, as it guides the small location to change with input masks (in our experiments, instances are pretty a small portion of the full image).

However, as you have the paired data, I recommend to modify InstaGAN to use **pix2pix** loss instead of CylceGAN loss. You can implement it by merging pi2pix model and instangan model in this repository.
